galaxy_info:
  author: yoshiaki tanaka
  description: install python base packages
  license: MIT
  min_ansible_version: 2.4
  platforms:
  - name: Debian
    versions:
      - stretch
  galaxy_tags: []

dependencies: []
