---
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: stretch
      box: histudy/stretch
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 1
  instances:
    - name: apt-backports
      ansible_groups:
        - stretch
verifier:
  name: serverspec
